on:
  push:
    branches:
      - master

name: Aikido Scan
jobs:
  aikido-local-scan-repo:
    runs-on: ubuntu-latest
    container:
      image: aikidosecurity/local-scanner:v1.0.131
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: cals-cli
      - name: Run scan
        run: |
          aikido-local-scanner scan cals-cli \
            --apikey ${{ secrets.AIKIDO_API_KEY }} \
            --linked-team-name aikido-liflig-internal \
            --repositoryname cals-cli \
            --branchname master
